name: terraform-ci
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  tf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: terraform-linters/setup-tflint@v4
      - name: Terraform fmt/validate
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate
      - name: TFLint
        run: |
          tflint --init
          tflint --module
      # plan (bez stanu zdalnego — tylko jako sanity-check)
      - name: Terraform plan (dry-run)
        run: |
          terraform init -backend=false
          terraform plan -input=false -lock=false || true
